/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import static Login.TaiKhoanController.index;
import static Main.ConnectionSQL.getConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;


    

public class DuKienLuongGiaoVienFrame extends javax.swing.JFrame {
    public static int flag = 0;

    public static String thongbao = "";
    public static String notify = "";
    
    
    public DuKienLuongGiaoVienFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        showData();
        System.out.println("flag = "+flag);
        if(flag == 0){
            btnXacNhan.setVisible(true);
        }
        else{
            btnXacNhan.setVisible(false);
            jLabel3.setText(thongbao);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnXacNhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(156, 16, 16));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TRƯỜNG TRUNG HỌC CƠ SỞ X");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edu.png"))); // NOI18N

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eduhat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel20)
                .addGap(208, 208, 208)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã cán bộ", "Họ tên", "Chức vụ", "Bậc", "Tháng", "Năm", "Lương cơ sở", "Lương cứng", "Phụ cấp chức vụ", "Phụ cấp thâm niên", "Tổng lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setBackground(new java.awt.Color(253, 253, 253));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dự kiến lương tháng 8 năm 2023:");

        jScrollPane2.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("- Mức lương cơ sở được áp dụng theo quy định của nhà nước (Nghị định 24/2023/NĐ-CP) chính thức từ ngày 1/72023.\n- Đối với mức lương cứng được tính bằng: Lương cơ sở * hệ số lương của giáo viên.\n- Đối với mức phụ cấp chức vụ được tính bằng: lương cơ sở * hệ số phụ cấp chức vụ ứng với giáo viên.\n- Đối với mức phụ cấp thâm niên được tính bằng: n% * lương cứng (với n là số năm mà giáo viên công tác tại trường, chỉ áp dụng đối\n  với giáo viên có thâm niên công tác từ 5 năm trở lên tại trường.");
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        btnXacNhan.setBackground(new java.awt.Color(156, 16, 16));
        btnXacNhan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(253, 253, 253));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel5.setBackground(new java.awt.Color(172, 172, 172));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("THÔNG TIN LƯƠNG DỰ KIẾN TRONG THÁNG");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        flag=1;
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("hh:mm - dd.MM.yyyy");
        
        int result = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc chắn xác nhận thông tin trên không? Sau khi xác nhận, thông tin về lương sẽ được thêm vào lịch sử lương!",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    btnXacNhan.setVisible(false);
                    notify = "Bảng lương dự kiến đã được xác nhận thành công vào lúc "+ft.format(date);
                    jLabel3.setText(notify);
                    
                    thongbao = "Đã nhận vào lúc "+ft.format(date);
                    
                    BangLuongChiTiet st = new BangLuongChiTiet(){};
                    st.setMaCB(index);
                    st.setThang(8);
                    st.setNam(2023);
                    st.setLuongCoSo(1800000);
                    st.setLuongCung(Integer.parseInt(jTable1.getValueAt(0, 7).toString()));
                    st.setPhuCapChucVu(Integer.parseInt(jTable1.getValueAt(0, 8).toString()));
                    st.setPhuCapThamNien(Integer.parseInt(jTable1.getValueAt(0, 9).toString()));
                    st.setTongLuong(Integer.parseInt(jTable1.getValueAt(0, 10).toString()));
                    st.setMaBangLuong(14);
                    
                    //System.out.println("bang luong chi tiet: "+st.getMaCB()+" - "+st.getMaBangLuong()+" - "+st.getThang()+" - "+st.getNam()+" - "+st.getLuongCoSo()+" - "+st.getLuongCung()+" - "+st.getPhuCapChucVu()+" - "+st.getPhuCapThamNien()+" - "+st.getTongLuong());
                    ConnectionSQL.InsertBangLuongChiTiet(st);
                   
                    
                }else if (result == JOptionPane.NO_OPTION){
                    jLabel3.setText("");
                }
                
        
    }//GEN-LAST:event_btnXacNhanActionPerformed
    
    
    public void showData(){
        String query = "select MaCB, ThoiGianBatDau, ThoiGianKetThuc from quatrinhluong where MaCB = '"+index+"' and ThoiGianKetThuc ='"+"2023'";
        System.out.println(query);
        int flag = 0;
        int batdau = 0;
        int ketthuc = 0;
        int year=0;
        String hoten="";
        try{
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                flag++;
                batdau = rs.getInt("ThoiGianBatDau");
                ketthuc = rs.getInt("ThoiGianKetThuc");
            }
            conn.close();
        }catch(Exception e){}
        
        if(flag==0){
            JOptionPane.showMessageDialog(null, "Cán bộ bạn tìm kiếm hiện đang không công tác tại trường!!!!");
            return;
        }
        else{
            year = ketthuc - batdau;
            
            //tính số năm công tác trong trường hợp làm tại trường lâu năm và nắm giữ nhiều chức vụ
            int count=0,temp=0;
            String query2 = "select ThoiGianBatDau, ThoiGianKetThuc from quatrinhluong where MaCB = '"+index+"' order by ThoiGianBatDau";
            System.out.println(query2);
            try{
                Connection conn2 = getConnection();
                Statement stmt2 = conn2.createStatement();
                ResultSet rs2 = stmt2.executeQuery(query2);
                while(rs2.next()){
                    if(temp != rs2.getInt("ThoiGianBatDau")) count =0;
                    count += rs2.getInt("ThoiGianKetThuc") - rs2.getInt("ThoiGianBatDau");
                    temp =rs2.getInt("ThoiGianKetThuc");
                    System.out.println("Cap count temp la "+count+" - "+temp);
                }
                conn2.close();
            }catch(Exception e){}
            
            
            DefaultTableModel tableModel;
            jTable1.getModel();
            tableModel=(DefaultTableModel)jTable1.getModel();
            tableModel.setRowCount(0);
            double heso = 0.0,hesophucap = 0.0;
            int bac = 0;
            String chucvu = "";
            String query1 = "select HeSo,HeSoPhuCap, HoTen, ChucVu, canbo.Bac from canbo, bacluong, phucapchucvu where canbo.Bac=bacluong.Bac and canbo.ChucVu = phucapchucvu.MaChucVu and MaCB ='"+index+"'";
            System.out.println(query1);
            try{
                Connection conn1 = getConnection();
                Statement stmt1 = conn1.createStatement();
                ResultSet rs1 = stmt1.executeQuery(query1);
                while(rs1.next()){
                    chucvu = rs1.getString("ChucVu");
                    heso = rs1.getDouble("HeSo");
                    hesophucap = rs1.getDouble("HeSoPhuCap");
                    hoten = rs1.getString("HoTen");
                    bac = rs1.getInt("Bac");
                }
                conn1.close();
            }
            catch(Exception e){}
        
            BangLuongChiTiet st = new BangLuongChiTiet(){};
                st.setMaCB(index);
                st.setThang(8);
                st.setNam(2023);
                st.setLuongCung(1800000*heso);
                st.setPhuCapChucVu(hesophucap*1800000);
                if(count>=5) st.setPhuCapThamNien((double)count/100*1800000);
                st.setTongLuong(st.getLuongCung()+st.getPhuCapChucVu()+st.getPhuCapThamNien());
                st.setMaBangLuong(14);
                
                //System.out.println("casn booj: "+st.getMaCB()+" - "+st.getLuongCung()+" - "+st.getPhuCapChucVu()+" - "+st.getPhuCapThamNien()+" - "+st.getTongLuong());
                
            tableModel.addRow(new Object[]{
                     st.getMaCB(), hoten,chucvu, bac, st.getThang(), st.getNam(), 1800000,(int) st.getLuongCung(),(int) st.getPhuCapChucVu(), (int) st.getPhuCapThamNien(),(int) st.getTongLuong()
                });
                
        }
        
        
        
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuKienLuongGiaoVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuKienLuongGiaoVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuKienLuongGiaoVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuKienLuongGiaoVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuKienLuongGiaoVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
